export default {
  login: 'theo82',
  id: 7755518,
  node_id: 'MDQ6VXNlcjc3NTU1MTg=',
  avatar_url: 'https://avatars.githubusercontent.com/u/7755518?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/theo82',
  html_url: 'https://github.com/theo82',
  followers_url: 'https://api.github.com/users/theo82/followers',
  following_url: 'https://api.github.com/users/theo82/following{/other_user}',
  gists_url: 'https://api.github.com/users/theo82/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/theo82/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/theo82/subscriptions',
  organizations_url: 'https://api.github.com/users/theo82/orgs',
  repos_url: 'https://api.github.com/users/theo82/repos',
  events_url: 'https://api.github.com/users/theo82/events{/privacy}',
  received_events_url: 'https://api.github.com/users/theo82/received_events',
  type: 'User',
  site_admin: false,
  name: 'Theodosios Tziomakas',
  company: 'https://github.com/theo82',
  blog: '',
  location: 'Larissa,Greece',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: 'Theo_Tziomakas',
  public_repos: 50,
  public_gists: 0,
  followers: 9,
  following: 16,
  created_at: '2014-05-31T17:03:37Z',
  updated_at: '2021-08-17T14:34:35Z',
}
